apiVersion: v1
kind: ConfigMap
metadata:
  name: gmontinny-config
  namespace: gmontinny
data:
  SPRING_PROFILES_ACTIVE: "prod"
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "gmontinny"
  POSTGRES_USER: "gmontinny"
  RABBITMQ_HOST: "rabbitmq-svc"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "gmontinny"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  VAULT_HOST: "vault-svc"
  VAULT_PORT: "8200"
  VAULT_ENABLED: "true"
  APP_BATCH_CHUNK_SIZE: "100"
  APP_BATCH_THREAD_POOL_SIZE: "4"
  APP_RATE_LIMIT_LOGIN_CAPACITY: "20"
  APP_RATE_LIMIT_API_CAPACITY: "200"
