apiVersion: v1
kind: ServiceAccount
metadata:
  name: gmontinny
  namespace: gmontinny
  labels:
    app: gmontinny
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gmontinny-role
  namespace: gmontinny
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gmontinny-rolebinding
  namespace: gmontinny
subjects:
  - kind: ServiceAccount
    name: gmontinny
    namespace: gmontinny
roleRef:
  kind: Role
  name: gmontinny-role
  apiGroup: rbac.authorization.k8s.io
