apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gmontinny-ingress
  namespace: gmontinny
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - gmontinny.example.com
      secretName: gmontinny-tls
  rules:
    - host: gmontinny.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gmontinny-svc
                port:
                  number: 80
