apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

images:
  - name: gmontinny
    newName: <acr_name>.azurecr.io/gmontinny
    newTag: latest
